title: "妖颜惑纵"
name: "妖颜惑纵"
description: "关于盛势(粽妖/峰峻cp)的花絮、正剧、直播、饭制剪辑等汇总"

markdown: kramdown
highlighter: rouge
javascript_enabled: true

#url: "https://eri129.github.io"
baseurl: "/fengjun"

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - drama.md
  - novel.md
  - fanvid.md
  - more.md
  - about.md

collections:
  novels:
    title: Novels
    default_open: true
    output: true

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
